name: Publish Module

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish_module:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Run type checking
        run: yarn typecheck

      - name: Run linting
        run: yarn lint

      - name: Build package
        run: yarn prepare

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes in source code
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'src/**'
              - 'android/**'
              - 'ios/**'
              - 'package.json'
              - 'README.md'

      - name: Generate release and update CHANGELOG
        if: steps.changes.outputs.src == 'true'
        run: |
          yarn release:auto
          git push --follow-tags origin main

      - name: Publish to npm
        if: steps.changes.outputs.src == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Prepare GitHub Packages publication
        if: steps.changes.outputs.src == 'true'
        run: |
          # Создаем package.json для GitHub Packages
          jq '.name = "@leonidmolchanov/react-native-cloudpayments" | .publishConfig.registry = "https://npm.pkg.github.com/"' package.json > package-github.json

      - name: Publish to GitHub Packages
        if: steps.changes.outputs.src == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Сохраняем оригинальные файлы
          cp package.json package.json.backup
          cp .npmrc .npmrc.backup 2>/dev/null || true
          
          # Настраиваем для GitHub Packages
          cp package-github.json package.json
          echo "@leonidmolchanov:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          
          # Публикуем в GitHub Packages
          npm publish --access public
          
          # Восстанавливаем оригинальные файлы
          mv package.json.backup package.json
          mv .npmrc.backup .npmrc 2>/dev/null || rm -f .npmrc
          rm -f package-github.json

      - name: Update documentation
        if: steps.changes.outputs.src == 'true'
        run: |
          # Trigger docs rebuild by updating docs workflow
          echo "Module published, documentation will be updated automatically" 